controllers:
    resource:
        path: ../src/Controller
        namespace: App\Controller
    type: attribute
    prefix: /

api:
    resource:
        path: ../src/Controller/Api
        namespace: App\Controller\Api
    type: attribute
    prefix: /api

auth:
    resource:
        path: ../src/Controller/Auth
        namespace: App\Controller\Auth
    type: attribute
    prefix: /auth
